# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
