# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20180323_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment',
            field=models.CharField(choices=[('cash', 'CASH'), ('paytm', 'PAYTM')], max_length=5),
        ),
    ]
