# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20180324_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True),
        ),
    ]
