# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-03 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_user_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
