# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20180403_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
