# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('SPONSOR', 'sponsor'), ('MARKETING', 'marketing'), ('STALL', 'stall')], max_length=5),
        ),
    ]
