# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180323_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('sponsor', 'SPONSOR'), ('marketing', 'MARKETING'), ('stall', 'STALL'), ('tshirt', 'TSHIRT')], max_length=5),
        ),
    ]
