# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180323_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payor', models.CharField(max_length=50)),
                ('payee', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bills')),
                ('date', models.DateField()),
                ('mode_of_payment', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('income', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='payor',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Expenditure',
        ),
    ]
